/* Trilingual glossary. Always shows all three languages side by side —
   the UI language only changes the headings and category names.          */

var GLOSS_META = {
  uk: { eyebrow:'Термінологія · три мови', h1:'Словник',
        lede:'Усі три мови поруч незалежно від вибраної. Пошук працює по всіх трьох одночасно — вводь українською, словацькою чи англійською.',
        ph:'Пошук у трьох мовах: сопло, dýza, nozzle…', of:'з',
        head:['Українська','Slovenčina','English'],
        cats:{ machine:'Машина і вузли', head_:'Голова і пальник', plasma:'Плазма',
               laser:'Лазер', water:'Воднострумінь', oxy:'Кисневе різання',
               cut:'Різання — поняття', cnc:'Програма і ЧПУ', elec:'Електрика',
               serv:'Сервіс і робота з клієнтом' } },
  sk: { eyebrow:'Terminológia · tri jazyky', h1:'Slovník',
        lede:'Všetky tri jazyky vedľa seba bez ohľadu na zvolený. Vyhľadávanie funguje naraz vo všetkých troch — píš po ukrajinsky, slovensky alebo anglicky.',
        ph:'Hľadať v troch jazykoch: dýza, сопло, nozzle…', of:'z',
        head:['Українська','Slovenčina','English'],
        cats:{ machine:'Stroj a uzly', head_:'Hlava a horák', plasma:'Plazma',
               laser:'Laser', water:'Vodný lúč', oxy:'Autogénne rezanie',
               cut:'Rezanie — pojmy', cnc:'Program a CNC', elec:'Elektrika',
               serv:'Servis a komunikácia so zákazníkom' } },
  en: { eyebrow:'Terminology · three languages', h1:'Glossary',
        lede:'All three languages side by side regardless of the interface language. Search covers all three at once — type in Ukrainian, Slovak or English.',
        ph:'Search across three languages: nozzle, dýza, сопло…', of:'of',
        head:['Українська','Slovenčina','English'],
        cats:{ machine:'Machine and assemblies', head_:'Head and torch', plasma:'Plasma',
               laser:'Laser', water:'Waterjet', oxy:'Oxy-fuel cutting',
               cut:'Cutting concepts', cnc:'Program and CNC', elec:'Electrical',
               serv:'Service and customer contact' } }
};

/* [category, ukrainian, slovak, english] */
var GLOSSARY = [
  ['machine','верстат / машина','stroj','machine'],
  ['machine','портал','portál','gantry'],
  ['machine','каретка','vozík','carriage'],
  ['machine','стіл','stôl','table'],
  ['machine','ламель','lamela','slat'],
  ['machine','вісь','os','axis'],
  ['machine','лінійні напрямні','lineárne vedenia','linear guides'],
  ['machine','рейка і шестерня','hrebeň a pastorok','rack and pinion'],
  ['machine','кулькова гвинтова передача','guľôčková skrutka','ballscrew'],
  ['machine','редуктор','prevodovka','gearbox'],
  ['machine','сервопривід','servopohon','servo drive'],
  ['machine','енкодер / датчик положення','enkodér / snímač polohy','encoder'],
  ['machine','шафа керування','rozvádzač','control cabinet'],
  ['machine','панель оператора','ovládací panel','operator console / HMI'],
  ['machine','система керування','riadiaci systém','control system'],
  ['machine','витяжка','odsávanie','fume extraction'],
  ['machine','водяний стіл','vodný stôl','water table'],
  ['machine','аварійний стоп','núdzové zastavenie','emergency stop'],
  ['machine','захист від зіткнення','ochrana proti kolízii','crash protection'],
  ['machine','кінцевий вимикач','koncový spínač','limit switch'],
  ['machine','референтна точка / хомінг','referovanie','homing'],
  ['machine','калібрування','kalibrácia','calibration'],
  ['machine','люфт','vôľa','backlash'],
  ['machine','помилка стеження','chyba sledovania','following error'],
  ['machine','обертання','otáčanie','rotation'],
  ['machine','нахил','naklonenie','tilt'],

  ['head_','пальник','horák','torch'],
  ['head_','різальна голова','rezacia hlava','cutting head'],
  ['head_','сопло','dýza','nozzle'],
  ['head_','електрод','elektróda','electrode'],
  ['head_','завихрювач','vírivý krúžok','swirl ring'],
  ['head_','захисний ковпак','ochranný kryt','shield cap'],
  ['head_','витратники / розхідники','spotrebný materiál','consumables'],
  ['head_','тримач','držiak','holder'],
  ['head_','висота пальника','výška horáka','torch height'],
  ['head_','контроль висоти','riadenie výšky','height control (THC)'],
  ['head_','пошук поверхні','hľadanie povrchu','initial height sensing (IHS)'],

  ['plasma','плазма','plazma','plasma'],
  ['plasma','дуга','oblúk','arc'],
  ['plasma','пілотна дуга','pilotný oblúk','pilot arc'],
  ['plasma','перенесена дуга','prenesený oblúk','transferred arc'],
  ['plasma','напруга дуги','napätie oblúka','arc voltage'],
  ['plasma','гафній','hafnium','hafnium'],
  ['plasma','вольфрам','volfrám','tungsten'],
  ['plasma','затискач маси','ukostrovacia svorka','work lead clamp'],
  ['plasma','заземлення','uzemnenie','earthing / grounding'],
  ['plasma','плазмовий газ','plazmový plyn','plasma gas'],
  ['plasma','захисний газ','ochranný plyn','shield gas'],
  ['plasma','підпал','zapálenie','ignition'],
  ['plasma','іонізація','ionizácia','ionisation'],

  ['laser','лазер','laser','laser'],
  ['laser','волокно','vlákno','fibre'],
  ['laser','волоконний лазер','vláknový laser','fibre laser'],
  ['laser','промінь','lúč','beam'],
  ['laser','джерело','zdroj','source / resonator'],
  ['laser','потужність','výkon','power'],
  ['laser','довжина хвилі','vlnová dĺžka','wavelength'],
  ['laser','лінза','šošovka','lens'],
  ['laser','колімувальна лінза','kolimačná šošovka','collimating lens'],
  ['laser','фокусувальна лінза','zaostrovacia šošovka','focusing lens'],
  ['laser','захисне скло','ochranné sklo','protective glass'],
  ['laser','фокус','ohnisko','focal point'],
  ['laser','положення фокуса','poloha ohniska','focal position'],
  ['laser','керамічне кільце','keramický krúžok','ceramic ring'],
  ['laser','ємнісний датчик','kapacitný snímač','capacitive sensor'],
  ['laser','допоміжний газ','asistenčný plyn','assist gas'],
  ['laser','юстування','justáž','alignment'],

  ['water','воднострумінь','vodný lúč','waterjet'],
  ['water','абразив','abrazívo','abrasive'],
  ['water','гранат','granát','garnet'],
  ['water','сопло-отвір','tryska','orifice'],
  ['water','фокусувальна трубка','zaostrovacia trubica','focusing tube'],
  ['water','змішувальна камера','zmiešavacia komora','mixing chamber'],
  ['water','насос','čerpadlo','pump'],
  ['water','інтенсифікатор','intenzifikátor','intensifier'],
  ['water','тиск','tlak','pressure'],
  ['water','ущільнення','tesnenie','seal'],
  ['water','зворотний клапан','spätný ventil','check valve'],
  ['water','конусність','kužeľovitosť','taper'],
  ['water','відставання струменя','zaostávanie lúča','jet lag'],

  ['oxy','кисневе різання','autogénne rezanie','oxy-fuel cutting'],
  ['oxy','кисень','kyslík','oxygen'],
  ['oxy','паливний газ','horľavý plyn','fuel gas'],
  ['oxy','пропан','propán','propane'],
  ['oxy','ацетилен','acetylén','acetylene'],
  ['oxy','мундштук','hubica','cutting tip'],
  ['oxy','підігрів','predhrev','preheat'],
  ['oxy','полум’я','plameň','flame'],
  ['oxy','зворотний удар полум’я','spätný šľah','flashback'],
  ['oxy','вогнеперепинювач','poistka proti šľahnutiu','flashback arrestor'],
  ['oxy','чистота газу','čistota plynu','gas purity'],

  ['cut','різання','rezanie','cutting'],
  ['cut','ширина різу','šírka rezu / rezná škára','kerf'],
  ['cut','компенсація ширини різу','korekcia šírky rezu','kerf compensation'],
  ['cut','пробивання','prepich','piercing'],
  ['cut','врізання','nábeh','lead-in'],
  ['cut','вихід','výbeh','lead-out'],
  ['cut','контур','kontúra','contour'],
  ['cut','скіс','úkos','bevel'],
  ['cut','шлак / окалина','troska','dross'],
  ['cut','зона термічного впливу','tepelne ovplyvnená oblasť','heat-affected zone'],
  ['cut','кромка','hrana','edge'],
  ['cut','лист','plech','sheet / plate'],
  ['cut','деталь','dielec','part'],
  ['cut','відхід','odpad','scrap'],
  ['cut','перемичка','mostík','microjoint / tab'],
  ['cut','розкрій','nesting','nesting'],
  ['cut','товщина','hrúbka','thickness'],
  ['cut','швидкість різання','rezná rýchlosť','cutting speed'],
  ['cut','подача','posuv','feed'],
  ['cut','допуск','tolerancia','tolerance'],
  ['cut','короблення','deformácia','distortion'],
  ['cut','труба','rúra','pipe / tube'],
  ['cut','профіль','profil','profile / beam'],
  ['cut','днище','dno','dome head'],
  ['cut','нержавіюча сталь','nerezová oceľ','stainless steel'],
  ['cut','конструкційна сталь','konštrukčná oceľ','mild steel'],
  ['cut','алюміній','hliník','aluminium'],

  ['cnc','програма','program','program'],
  ['cnc','G-код','G-kód','G-code'],
  ['cnc','траєкторія','dráha','toolpath'],
  ['cnc','постпроцесор','postprocesor','post-processor'],
  ['cnc','нульова точка','nulový bod','zero point / datum'],
  ['cnc','абсолютні координати','absolútne súradnice','absolute coordinates'],
  ['cnc','швидкий хід','rýchloposuv','rapid traverse'],
  ['cnc','креслення','výkres','drawing'],
  ['cnc','технічна документація','technická dokumentácia','technical documentation'],
  ['cnc','свердління','vŕtanie','drilling'],
  ['cnc','нарізання різьби','rezanie závitov','tapping'],
  ['cnc','маркування','značenie','marking'],
  ['cnc','фрезерування','frézovanie','milling'],

  ['elec','напруга','napätie','voltage'],
  ['elec','струм','prúd','current'],
  ['elec','опір','odpor','resistance'],
  ['elec','постійний струм','jednosmerný prúd','direct current (DC)'],
  ['elec','змінний струм','striedavý prúd','alternating current (AC)'],
  ['elec','запобіжник','poistka','fuse'],
  ['elec','контактор','stýkač','contactor'],
  ['elec','реле','relé','relay'],
  ['elec','частотний перетворювач','frekvenčný menič','frequency inverter (VFD)'],
  ['elec','електрична схема','elektrická schéma','wiring diagram'],
  ['elec','мультиметр','multimeter','multimeter'],
  ['elec','наведення / завади','rušenie','interference (EMI)'],
  ['elec','екранування','tienenie','shielding'],
  ['elec','кабель','kábel','cable'],
  ['elec','обрив','prerušenie','open circuit'],
  ['elec','коротке замикання','skrat','short circuit'],
  ['elec','електротехнічне освідчення','elektrotechnické osvedčenie','electrical certificate'],

  ['serv','несправність','porucha','fault / breakdown'],
  ['serv','симптом','príznak','symptom'],
  ['serv','причина','príčina','cause'],
  ['serv','діагностика','diagnostika','diagnostics'],
  ['serv','усунення несправності','odstránenie poruchy','troubleshooting'],
  ['serv','ремонт','oprava','repair'],
  ['serv','обслуговування','údržba','maintenance'],
  ['serv','запчастина','náhradný diel','spare part'],
  ['serv','заміна','výmena','replacement'],
  ['serv','дистанційно','na diaľku','remotely'],
  ['serv','виїзд до клієнта','výjazd k zákazníkovi','site visit'],
  ['serv','службова поїздка','služobná cesta','business trip'],
  ['serv','журнал аварій','denník alarmov','alarm log'],
  ['serv','повідомлення про помилку','chybové hlásenie','error message'],
  ['serv','параметри','parametre','parameters'],
  ['serv','налаштування','nastavenie','setting'],
  ['serv','резервна копія','záloha','backup'],
  ['serv','оновлення ПЗ','aktualizácia softvéru','software update'],
  ['serv','зношений','opotrebovaný','worn'],
  ['serv','протікання','únik / netesnosť','leak'],
  ['serv','простій','prestoj','downtime'],
  ['serv','гарантія','záruka','warranty'],
  ['serv','замовник','zákazník','customer'],
  ['serv','оператор','obsluha','operator'],
  ['serv','навчання','školenie','training'],
  ['serv','звіт / протокол','protokol','report'],
  ['serv','приймання','preberanie','handover / acceptance'],
  ['serv','введення в експлуатацію','uvedenie do prevádzky','commissioning'],
  ['serv','безпека праці','bezpečnosť práce','occupational safety']
];
