/* Interview questions with model answers, three languages.
   Rendered as <details> so the answer stays hidden until tapped.        */

var IV_META = {
  uk: { eyebrow:'Підготовка · питання і відповіді', h1:'Співбесіда',
        lede:'Спершу спробуй відповісти сам, потім розкрий. Відповіді написані так, щоб їх можна було сказати вголос за 30–60 секунд, а не зачитати.',
        hint:'торкнись, щоб побачити відповідь',
        cats:{ tech:'Технології різання', plasma:'Плазма', laser:'Лазер', elec:'Електрика',
               think:'Мислення й діагностика', client:'Робота з клієнтом',
               org:'Організаційні', case:'Ситуаційні кейси' } },
  sk: { eyebrow:'Príprava · otázky a odpovede', h1:'Pohovor',
        lede:'Najprv skús odpovedať sám, potom rozbaľ. Odpovede sú napísané tak, aby sa dali povedať nahlas za 30–60 sekúnd, nie prečítať.',
        hint:'ťuknutím zobrazíš odpoveď',
        cats:{ tech:'Rezacie technológie', plasma:'Plazma', laser:'Laser', elec:'Elektrika',
               think:'Myslenie a diagnostika', client:'Práca so zákazníkom',
               org:'Organizačné', case:'Situačné otázky' } },
  en: { eyebrow:'Preparation · questions and answers', h1:'Interview',
        lede:'Try answering first, then open. The answers are written to be spoken in 30–60 seconds, not read out.',
        hint:'tap to reveal the answer',
        cats:{ tech:'Cutting technologies', plasma:'Plasma', laser:'Laser', elec:'Electrical',
               think:'Reasoning and diagnosis', client:'Working with the customer',
               org:'Practicalities', case:'Situational questions' } }
};

var INTERVIEW = {
uk: [
['tech','Які технології різання ви знаєте і чим вони відрізняються?',
 'Чотири. <b>Плазма</b> — дуга плавить метал, закручений газ видуває розплав; ріже все струмопровідне. <b>Лазер</b> — сфокусований промінь, найвища точність, найтонший рез, але обмежений по товщині. <b>Воднострумінь</b> — єдиний холодний процес: абразив стирає матеріал, тому немає зони термічного впливу і ріже будь-що. <b>Кисень</b> — там ріже хімія: залізо горить у кисні, і це працює лише на конструкційній сталі, зате до 300 мм.'],
['tech','Коли ви обрали б лазер, а коли плазму?',
 'До приблизно 25 міліметрів лазер швидший і дає незрівнянно кращу кромку. Вище плазма його переганяє, а після 50 лазер уже практично не варіант. Ця межа рухається вгору з ростом потужності джерел — десять років тому вона була на 12–15 мм. Але є нюанс: на товстому металі лазер довго пробиває, тому деталь із багатьма отворами може вийти швидше на плазмі, навіть якщо сам рез лазер робить хутчіше.'],
['tech','Чому киснем не можна різати нержавійку?',
 'Процес тримається на тому, що оксид плавиться нижче за сам метал — тоді струмінь кисню його видуває. У залізі так і є: оксид заліза плавиться близько 1370 °C, саме залізо при 1538. У нержавійці навпаки — оксид хрому тугоплавкий, близько 2400 °C. Коли сталь уже рідка, оксид ще твердий: він утворює кірку, перекриває доступ кисню, і реакція гасне. Це та сама плівка, завдяки якій нержавійка не іржавіє.'],
['tech','Що таке ширина різу і навіщо її компенсують?',
 'Інструмент забирає смугу металу: у плазми це 1,5–4 мм, у лазера 0,1–0,4. Якщо вести пальник рівно по контуру, деталь вийде меншою на половину цієї ширини з кожного боку. Тому машина зміщує траєкторію — назовні для зовнішнього контуру, всередину для отворів. Вмикають компенсацію завжди на врізанні, ніколи на самому контурі, інакше в місці вмикання лишиться сходинка.'],
['tech','Чому внутрішні отвори ріжуть раніше за зовнішній контур?',
 'Бо щойно відрізаний зовнішній контур, деталь провалюється або зсувається. Усі отвори після цього будуть не на місці або взагалі у відході. Це правило, а не стиль — і воно видно в програмі за десять секунд, без запуску машини.'],

['plasma','З чого складається плазмовий пальник?',
 'Чотири витратники. <b>Електрод</b> — мідь із гафнієвою вставкою, це катод. <b>Завихрювач</b> — кільце з похилими отворами, закручує газ і стискає дугу. <b>Сопло</b> — отвір, що протискає дугу; саме стиснення й робить плазму різальним інструментом. <b>Захисний ковпак</b> — формує вторинний потік і приймає бризки. Ресурс рахують не в метрах різу, а в кількості пробивань.'],
['plasma','Що таке пілотна дуга і навіщо вона потрібна?',
 'Між електродом і деталлю повітря, а воно струм не проводить — дуга не може виникнути з нічого. Тому її спершу запалюють усередині пальника, між електродом і соплом. Газ видуває цю дугу назовні, вона створює провідний канал, і щойно він дістає деталі, струм перескакує на неї. Далі ріже вже перенесена дуга, а сопло виходить з кола. Якщо перенесення не відбувається, пілот далі горить у сопло й вигорає за секунди.'],
['plasma','Як працює контроль висоти пальника?',
 'Джерело стабілізує струм, а не напругу. Тому напруга вільна і прямо залежить від довжини дуги: довша дуга — вища напруга. Система тримає задану напругу, підправляючи вісь Z, і пальник іде за нерівним листом автоматично. Перед різанням окремо працює пошук поверхні. Важливо, що знос витратників змінює напругу при тій самій висоті — тому коли контроль висоти «дуріє», першими перевіряють витратники, а не датчик.'],
['plasma','Чому в електроді гафній, а не вольфрам?',
 'Вольфрам сам по собі кращий емітер — плавиться близько 3400 °C і живе довше. Але він миттєво окислюється, тому в кисні чи навіть у повітрі згорить за секунди. Гафній гірший емітер, зате утворює тугоплавкий оксид, який витримує процес. Тобто гафній — це вимушений компроміс заради кисню. Для азоту й H35, де кисню немає, якраз ставлять вольфрам.'],

['laser','Чим волоконний лазер відрізняється від CO₂?',
 'Довжиною хвилі й тим, як ведеться промінь. У волоконного це близько 1,07 мкм і промінь іде оптичним волокном — ні дзеркал, ні юстування. Метали цю хвилю поглинають значно краще, тому він бере навіть мідь і латунь, які CO₂ майже не ріже, і має в рази вищий ККД. CO₂ має 10,6 мкм і систему дзеркал, зате добре ріже неметали — акрил, дерево, шкіру. Сьогодні в металі майже всюди волокно.'],
['laser','Навіщо потрібен допоміжний газ?',
 'Промінь тільки плавить, а розплав із різу видуває газ. Плюс газ визначає характер кромки. Кисень на конструкційній сталі вступає в екзотермічну реакцію й сам додає енергії — швидше, але кромка окислена. Азот інертний, лише видуває: кромка чиста, одразу під зварювання, але потрібен високий тиск і більша потужність. Повітря — дешевий компроміс, якщо воно сухе й без масла.'],
['laser','Як лазер міряє висоту, якщо дуги немає?',
 'Ємнісно. Сопло працює як обкладка конденсатора відносно листа: чим ближче, тим більша ємність. Система тримає задане значення, рухаючи вісь Z. Щоб це працювало, сопло має бути електрично ізольоване від корпусу — цю ізоляцію дає керамічне кільце. Тому бризки або тріщина на кераміці ламають вимірювання: з’являється провідний місток, і голова починає стрибати або битися в лист.'],

['elec','Що таке сервопривід і як він знає своє положення?',
 'Це двигун із замкненим контуром керування. Контролер задає положення, <b>енкодер</b> на валу повідомляє фактичне, а привід постійно доганяє різницю. Саме тому сервопривід відрізняється від крокового: він знає, де реально перебуває, а не припускає. Якщо привід не встигає за завданням, різниця росте і система видає помилку стеження — причина зазвичай механічна: опір, знос або неправильні параметри.'],
['elec','Як перевірити мультиметром, чи цілий запобіжник?',
 'Два способи. Знеструмити й поміряти опір або проzvонити: цілий дає майже нуль ом і писк, згорілий — обрив. Або, не виймаючи, поміряти напругу на самому запобіжнику під навантаженням: на цілому вона близька до нуля, на згорілому буде повна напруга живлення. Другий спосіб швидший, але вимагає обережності, бо ланцюг під напругою.'],
['elec','Чим відрізняється контактор від реле?',
 'Принцип однаковий — електромагніт замикає контакти. Різниця в призначенні й струмах. <b>Контактор</b> комутує силові кола: двигуни, нагрівачі, великі струми. У нього масивні контакти й дугогасильна камера, бо при розмиканні виникає дуга. <b>Реле</b> працює в колах керування й сигналів, на малих струмах, і воно менше й дешевше. Спрощено: реле передає команду, контактор передає потужність.'],
['elec','Чи вмієте читати електричну схему?',
 'Так, на рівні простеження кола від симптому: знайти елемент, зрозуміти, звідки приходить живлення й куди йде сигнал, визначити, де саме перевіряти. Технічну документацію я читав під час навчання, і англійська для позначень не проблема. Умовні позначення конкретного виробника доберу швидко — принцип скрізь той самий.'],

['think','Як ви шукаєте причину несправності?',
 'Спершу звужую, а не вгадую. Питаю, що змінилося з учора, коли почалося, це щоразу чи інколи, який матеріал і що востаннє міняли. Найважливіше розділення — чи це на кожній програмі, чи тільки на одній: одна відповідь ділить проблему навпіл. Далі ізолюю, де причина: машина, програма, витратники чи матеріал. І обов’язково перевіряю результат — «зараз працює» мене не влаштовує, бо якщо я не знаю чому, за тиждень воно повернеться.'],
['think','Розкажіть про складну проблему, яку ви вирішили.',
 'При обробці даних у мене вийшло 568 записів замість 569. Нічого не впало, помилки не було, програма відпрацювала нормально. Різницю показало лише порівняння з незалежним числом із джерела. Відтоді я не довіряю тому, що щось правильне лише тому, що воно відпрацювало без скарг — результат треба звіряти з чимось зовнішнім. Для сервісу це те саме: «машина запустилась» ще не означає, що несправність усунена.'],
['think','Що ви робите, якщо не знаєте відповіді?',
 'Кажу, що не знаю, і одразу кажу, як дізнаюся: подивлюся документацію, журнал аварій, спитаю колегу. Перед клієнтом вигадувати не можна — неправильна відповідь коштує дорожче за паузу, бо він за нею почне щось робити. Чесне «перевірю й передзвоню за годину» зберігає довіру, вигадка її руйнує назавжди.'],

['client','Як пояснити технічну проблему нетехнічній людині?',
 'Без термінів і в такому порядку: що сталося, чому, що робимо далі й скільки це займе. Людині потрібен не діагноз, а розуміння, коли вона знову працюватиме. Наприкінці корисно попросити переказати план своїми словами — так одразу видно, чи мене зрозуміли. Мені це дається легко: я вчився словацькою, працював із людьми в гастрономії, і пояснювати доводилося постійно.'],
['client','Клієнт кричить, бо в нього стоїть виробництво. Ваші дії?',
 'Спершу даю договорити й не сперечаюся. Потім визнаю проблему прямо — так, машина стоїть, і це коштує грошей щогодини. І одразу даю конкретику: що я роблю зараз і коли буде наступна інформація. Люди кричать від невизначеності, а не від поломки, і щойно з’являється план із часом, напруга спадає. Виправдовуватись і шукати винних у цей момент — найгірше, що можна зробити.'],
['client','Що робити, якщо поломка сталася через помилку оператора?',
 'Ніколи не казати «ви зробили неправильно». Кажу «давайте разом подивимось, що сталося», і ми проходимо послідовність. Людина зазвичай сама доходить висновку — і це набагато краще, ніж почути це від мене. У звіті описую нейтрально, фактами. І пропоную показати правильний порядок дій, щоб не повторилося. Мета — щоб клієнт наступного разу подзвонив нам, а не мовчав і зламав більше.'],

['org','Як ви ставитесь до закордонних відряджень?',
 'Позитивно, і жодних перешкод не маю — ні сімейних, ні інших. Закордонний паспорт є, їздити люблю. П’ять днів на місяць, як у вас зазначено, для мене абсолютно нормально. Я сприймаю відрядження як частину цієї роботи, а не як жертву: це саме та частина, де вчишся найшвидше.'],
['org','Маєте закордонний паспорт і водійський досвід?',
 'Так, паспорт є. Водійське посвідчення групи B, активний водій. Питання поїздки автомобілем до клієнта для мене не проблема.'],
['org','Яка ваша англійська на практиці?',
 'Рівень B2. Технічну документацію читаю щодня — я працюю з програмуванням, а там усе англійською. Усно тримаю робочу розмову: пояснити проблему, домовитись, уточнити. Не претендую на вільну, але для роботи з клієнтом і документацією достатньо, і при щоденному використанні швидко підтягнеться.'],
['org','Які у вас зарплатні очікування?',
 'Я орієнтуюсь на рівень початкової позиції сервісного техніка на словацькому ринку. Але мені важливіше зрозуміти повний обсяг: скільки виїздів, які надбавки за відрядження, як виглядає зростання після заучення. Якщо ви назвете діапазон для цієї позиції, я скажу, чи він мені підходить.'],

['case','Клієнт каже, що машина ріже гірше, ніж учора. З чого почнете?',
 'З двох питань: що змінилося з учора і чи це на кожній програмі, чи тільки на одній. Якщо на всіх — проблема в машині або витратниках, і витратники перевіряю першими, бо вони зношуються поступово й дають саме таке «раптове» погіршення. Якщо на одній програмі — причина в самій програмі чи параметрах. Далі прошу сфотографувати кромку: за характером шлаку й скосу вже видно, у який бік дивитися.'],
['case','Деталі виходять стабільно меншими на два міліметри. Де шукатимете?',
 'Це майже напевно ширина різу в CAM, а не машина. Ключове слово «стабільно» — механічна несправність давала б розкид, а не однаковий систематичний зсув на всіх деталях. Перевірю, чи всі розміри менші, чи лише зовнішні: якщо отвори навпаки більші, це остаточно підтверджує компенсацію. Потім тестова деталь із заміром.'],
['case','Оператор каже, що сопла не живуть і тижня. Ваші версії?',
 'Перша й найімовірніша — невдалі підпали. Якщо дуга не переноситься на деталь, пілот далі горить у сопло й випалює його за секунди; кілька таких спроб за зміну вбивають сопло. Тому перевіряю висоту пошуку поверхні, контакт маси й тиск газу. Друга версія — поставили не той комплект: сопло не під той струм або електрод не під той газ. І третя — занизька висота пробивання, тоді сопло вбивають бризки.'],
['case','Керування збоїть, але тільки в момент підпалу дуги. Що це?',
 'Майже напевно електромагнітні наведення, а не несправність електроніки. Високочастотний підпал — це потужний генератор широкосмугового шуму. Ключ у формулюванні клієнта: збій прив’язаний рівно до моменту підпалу, а не стається випадково. Дивитимусь заземлення — чи воно зіркою в одну точку, стан кабеля маси, екранування сигнальних кабелів і чи не йдуть вони в одному лотку із силовими.']
],

sk: [
['tech','Aké rezacie technológie poznáte a čím sa líšia?',
 'Štyri. <b>Plazma</b> — oblúk taví kov a zvírený plyn vyfukuje taveninu; reže všetko vodivé. <b>Laser</b> — sústredený lúč, najvyššia presnosť a najužšia škára, ale obmedzený hrúbkou. <b>Vodný lúč</b> — jediný studený proces: abrazívo materiál obrusuje, takže niet tepelne ovplyvnenej oblasti a reže sa takmer všetko. <b>Autogén</b> — tam reže chémia: železo horí v kyslíku, funguje to len na konštrukčnej oceli, zato do 300 mm.'],
['tech','Kedy by ste zvolili laser a kedy plazmu?',
 'Zhruba do 25 milimetrov je laser rýchlejší a dáva neporovnateľne lepšiu hranu. Nad tým ho plazma predbehne a nad 50 už laser prakticky nie je možnosť. Tá hranica sa s rastúcim výkonom zdrojov posúva nahor — pred desiatimi rokmi bola na 12–15 mm. Je tu ale jeden detail: na hrubom materiáli laser dlho prepichuje, takže dielec s veľa otvormi môže byť rýchlejší na plazme, aj keď samotný rez zvládne laser skôr.'],
['tech','Prečo sa nerez nedá rezať autogénom?',
 'Proces stojí na tom, že oxid sa taví nižšie ako samotný kov — potom ho prúd kyslíka vyfúkne. Pri železe to platí: oxid železa okolo 1370 °C, železo až 1538. Pri nereze je to naopak — oxid chrómu je žiaruvzdorný, okolo 2400 °C. Keď je oceľ už tekutá, oxid je stále tuhý: vytvorí kôru, zabráni prístupu kyslíka a reakcia zhasne. Je to tá istá vrstva, vďaka ktorej nerez nehrdzavie.'],
['tech','Čo je rezná škára a prečo sa koriguje?',
 'Nástroj odoberie pás materiálu: pri plazme 1,5–4 mm, pri laseri 0,1–0,4. Keby horák išiel presne po kontúre, dielec by bol menší o polovicu tejto šírky z každej strany. Preto stroj dráhu posunie — von pri vonkajšej kontúre, dnu pri otvoroch. Korekcia sa zapína vždy na nábehu, nikdy na samotnej kontúre, inak v mieste zapnutia ostane schod.'],
['tech','Prečo sa vnútorné otvory režú pred vonkajšou kontúrou?',
 'Lebo hneď ako sa odreže vonkajšia kontúra, dielec prepadne alebo sa posunie. Všetky otvory po nej budú mimo alebo rovno v odpade. Je to pravidlo, nie štýl — a v programe to vidno za desať sekúnd bez spustenia stroja.'],

['plasma','Z čoho sa skladá plazmový horák?',
 'Zo štyroch spotrebných dielov. <b>Elektróda</b> — meď s hafniovou vložkou, je to katóda. <b>Vírivý krúžok</b> — krúžok so šikmými otvormi, zviri plyn a zúži oblúk. <b>Dýza</b> — otvor, ktorý oblúk pretlačí; práve to zúženie robí z plazmy rezací nástroj. <b>Ochranný kryt</b> — tvaruje sekundárny prúd a zachytáva rozstrek. Životnosť sa počíta v počte prepichov, nie v metroch rezu.'],
['plasma','Čo je pilotný oblúk a načo slúži?',
 'Medzi elektródou a dielcom je vzduch, ktorý prúd nevedie — oblúk nemôže vzniknúť z ničoho. Preto sa najprv zapáli vnútri horáka, medzi elektródou a dýzou. Plyn ho vyfúkne von, vznikne vodivý kanál, a len čo dosiahne dielec, prúd naň preskočí. Ďalej reže už prenesený oblúk a dýza vypadne z obvodu. Ak k prenosu nedôjde, pilot horí do dýzy a vypáli ju za pár sekúnd.'],
['plasma','Ako funguje riadenie výšky horáka?',
 'Zdroj stabilizuje prúd, nie napätie. Preto je napätie voľné a priamo závisí od dĺžky oblúka: dlhší oblúk, vyššie napätie. Systém drží zadanú hodnotu dorovnávaním osi Z, takže horák kopíruje aj pokrivený plech. Pred rezaním ešte prebehne hľadanie povrchu. Dôležité je, že opotrebenie mení napätie pri rovnakej výške — takže keď riadenie výšky „šalie", prvé kontrolujem spotrebný materiál, nie snímač.'],
['plasma','Prečo je v elektróde hafnium a nie volfrám?',
 'Volfrám je sám osebe lepší emitor — taví sa okolo 3400 °C a vydrží dlhšie. Lenže sa okamžite oxiduje, takže v kyslíku či dokonca vo vzduchu zhorí za sekundy. Hafnium je horší emitor, zato vytvorí žiaruvzdorný oxid, ktorý proces znesie. Hafnium je teda nutný kompromis kvôli kyslíku. Pri dusíku a H35, kde kyslík nie je, sa práve dáva volfrám.'],

['laser','Aký je rozdiel medzi vláknovým a CO₂ laserom?',
 'Vlnovou dĺžkou a spôsobom vedenia lúča. Vláknový má okolo 1,07 µm a lúč ide optickým vláknom — žiadne zrkadlá, žiadna justáž. Kovy túto vlnu pohlcujú oveľa lepšie, takže zvládne aj meď a mosadz, ktoré CO₂ takmer nereže, a má mnohonásobne vyššiu účinnosť. CO₂ má 10,6 µm a sústavu zrkadiel, zato dobre reže nekovy — akrylát, drevo, kožu. Dnes je v kove takmer všade vláknový.'],
['laser','Načo slúži asistenčný plyn?',
 'Lúč len taví, taveninu zo škáry vyfukuje plyn. Zároveň plyn určuje charakter hrany. Kyslík na konštrukčnej oceli vstupuje do exotermickej reakcie a sám pridáva energiu — rýchlejšie, ale hrana ostáva oxidovaná. Dusík je inertný, iba vyfukuje: hrana je čistá, hneď pod zvar, ale treba vysoký tlak a vyšší výkon. Vzduch je lacný kompromis, ak je suchý a bez oleja.'],
['laser','Ako laser meria výšku, keď nie je oblúk?',
 'Kapacitne. Dýza funguje ako doska kondenzátora voči plechu: čím bližšie, tým väčšia kapacita. Systém drží zadanú hodnotu pohybom osi Z. Aby to fungovalo, musí byť dýza elektricky izolovaná od tela hlavy — tú izoláciu zabezpečuje keramický krúžok. Preto rozstrek alebo prasklina na keramike meranie pokazia: vznikne vodivý mostík a hlava začne skákať alebo naráža do plechu.'],

['elec','Čo je servopohon a ako pozná svoju polohu?',
 'Je to motor s uzavretou reguláciou. Riadenie zadá polohu, <b>enkodér</b> na hriadeli hlási skutočnú a pohon rozdiel priebežne dorovnáva. Práve tým sa líši od krokového motora: vie, kde naozaj je, nie kde by mal byť. Ak pohon nestíha zadanie, rozdiel narastá a systém hlási chybu sledovania — príčina býva mechanická: odpor, opotrebenie alebo zle nastavené parametre.'],
['elec','Ako multimetrom overíte, či je poistka celá?',
 'Dvoma spôsobmi. Odpojiť napájanie a zmerať odpor alebo prezvoniť: celá dá takmer nula ohmov a pípne, prepálená ukáže prerušenie. Alebo bez vyberania zmerať napätie priamo na poistke pod záťažou: na celej je takmer nulové, na prepálenej bude plné napájacie napätie. Druhý spôsob je rýchlejší, ale treba opatrnosť, lebo obvod je pod napätím.'],
['elec','Aký je rozdiel medzi stýkačom a relé?',
 'Princíp je rovnaký — elektromagnet spína kontakty. Rozdiel je v účele a prúdoch. <b>Stýkač</b> spína silové obvody: motory, ohrievače, veľké prúdy. Má masívne kontakty a zhášaciu komoru, lebo pri rozopnutí vzniká oblúk. <b>Relé</b> pracuje v riadiacich a signálových obvodoch, na malých prúdoch, a je menšie a lacnejšie. Zjednodušene: relé prenáša príkaz, stýkač prenáša výkon.'],
['elec','Viete čítať elektrickú schému?',
 'Áno, na úrovni sledovania obvodu od príznaku: nájsť prvok, pochopiť, odkiaľ prichádza napájanie a kam ide signál, a určiť, kde presne merať. Technickú dokumentáciu som čítal počas štúdia a angličtina pri označeniach nie je problém. Konvencie konkrétneho výrobcu si osvojím rýchlo — princíp je všade rovnaký.'],

['think','Ako postupujete pri hľadaní príčiny poruchy?',
 'Najprv zužujem, nehádam. Pýtam sa, čo sa zmenilo od včera, kedy to začalo, či je to vždy alebo občas, aký materiál a čo sa naposledy menilo. Najdôležitejšie rozdelenie je, či je to na každom programe alebo len na jednom — tá jedna odpoveď rozdelí problém na polovicu. Potom izolujem, kde príčina je: stroj, program, spotrebný materiál alebo materiál zákazníka. A výsledok si vždy overím — „teraz to ide" mi nestačí, lebo ak neviem prečo, o týždeň sa to vráti.'],
['think','Opíšte zložitý problém, ktorý ste vyriešili.',
 'Pri spracovaní údajov mi vyšlo 568 záznamov namiesto 569. Nič nespadlo, žiadne chybové hlásenie, program zbehol normálne. Rozdiel odhalilo až porovnanie s nezávislým číslom zo zdroja. Odvtedy neverím tomu, že je niečo správne len preto, že to prebehlo bez sťažností — výsledok treba overiť proti niečomu zvonku. V servise je to to isté: „stroj sa rozbehol" ešte neznamená, že porucha je odstránená.'],
['think','Čo urobíte, keď neviete odpoveď?',
 'Poviem, že neviem, a hneď aj to, ako to zistím: pozriem dokumentáciu, denník alarmov, opýtam sa kolegu. Pred zákazníkom si vymýšľať nemožno — nesprávna odpoveď stojí viac ako pauza, lebo zákazník podľa nej začne konať. Úprimné „overím si to a ozvem sa o hodinu" dôveru udrží, výmysel ju zničí natrvalo.'],

['client','Ako vysvetlíte technický problém netechnickému človeku?',
 'Bez odbornej hantýrky a v tomto poradí: čo sa stalo, prečo, čo robíme ďalej a ako dlho to potrvá. Človek nepotrebuje diagnózu, ale vedieť, kedy bude zase vyrábať. Na konci je dobré nechať si plán zopakovať vlastnými slovami — hneď vidno, či mi rozumeli. Ide mi to prirodzene: študoval som po slovensky a v gastre som denne pracoval s ľuďmi.'],
['client','Zákazník kričí, lebo mu stojí výroba. Čo urobíte?',
 'Najprv ho nechám dohovoriť a nehádam sa. Potom problém priamo priznám — áno, stroj stojí a stojí to peniaze každú hodinu. A hneď dám konkrétum: čo robím teraz a kedy bude ďalšia informácia. Ľudia kričia z neistoty, nie z poruchy, a len čo je na stole plán s časom, napätie klesne. Vyhovárať sa a hľadať vinníka je v tej chvíli to najhoršie.'],
['client','Čo ak poruchu spôsobila chyba obsluhy?',
 'Nikdy nepoviem „urobili ste to zle". Poviem „poďme sa spolu pozrieť, čo sa stalo", a prejdeme postupnosť. Človek k záveru zvyčajne dôjde sám — a to je oveľa lepšie, ako keby to počul odo mňa. Do protokolu to zapíšem neutrálne, faktami. A ponúknem, že ukážem správny postup, aby sa to neopakovalo. Cieľom je, aby zákazník nabudúce zavolal, a nie mlčal a pokazil viac.'],

['org','Ako sa staviate k zahraničným služobným cestám?',
 'Pozitívne a nemám žiadne prekážky — ani rodinné, ani iné. Cestovný pas mám, cestovanie ma baví. Päť dní mesačne, ako uvádzate, je pre mňa úplne v poriadku. Služobné cesty beriem ako súčasť tejto práce, nie ako obeť: je to práve tá časť, kde sa človek naučí najviac.'],
['org','Máte cestovný pas a skúsenosti s vedením auta?',
 'Áno, pas mám. Vodičský preukaz skupiny B, som aktívny vodič. Cesta autom k zákazníkovi pre mňa nie je problém.'],
['org','Ako ste na tom s angličtinou v praxi?',
 'Úroveň B2. Technickú dokumentáciu čítam denne — venujem sa programovaniu a tam je všetko po anglicky. Ústne zvládnem pracovný rozhovor: vysvetliť problém, dohodnúť sa, doplniť si informácie. Netvrdím, že som plynulý, ale na prácu so zákazníkom a dokumentáciou to stačí a pri dennom používaní sa to rýchlo zlepší.'],
['org','Aké máte platové očakávania?',
 'Orientujem sa na úroveň nástupnej pozície servisného technika na slovenskom trhu. Dôležitejšie je pre mňa pochopiť celý rozsah: koľko výjazdov, aké sú príplatky za služobné cesty a ako vyzerá rast po zaškolení. Ak poviete rozpätie pre túto pozíciu, rád poviem, či mi sedí.'],

['case','Zákazník hovorí, že stroj reže horšie ako včera. Čím začnete?',
 'Dvoma otázkami: čo sa zmenilo od včera a či je to na každom programe alebo len na jednom. Ak na všetkých, problém je v stroji alebo v spotrebnom materiáli — a spotrebný materiál kontrolujem prvý, lebo sa opotrebuje postupne a spôsobí presne takéto „náhle" zhoršenie. Ak len na jednom programe, príčina je v programe alebo v parametroch. Potom poprosím odfotiť hranu: z charakteru trosky a úkosu už vidno, ktorým smerom ísť.'],
['case','Dielce sú trvalo menšie o dva milimetre. Kde budete hľadať?',
 'Takmer isto je to šírka rezu v CAM, nie stroj. Kľúčové slovo je „trvalo" — mechanická porucha by dala rozptyl, nie rovnaký systematický posun na všetkých dielcoch. Overím, či sú menšie všetky rozmery, alebo len vonkajšie: ak sú otvory naopak väčšie, korekciu to definitívne potvrdí. Potom testovací dielec a premeranie.'],
['case','Obsluha tvrdí, že dýzy nevydržia ani týždeň. Aké máte verzie?',
 'Prvá a najpravdepodobnejšia sú neúspešné zapálenia. Ak sa oblúk neprenesie na dielec, pilot horí do dýzy a vypáli ju za sekundy; pár takých pokusov za zmenu dýzu zlikviduje. Preto kontrolujem výšku hľadania povrchu, ukostrenie a tlak plynu. Druhá verzia — nasadili nesprávnu sadu: dýza nie na ten prúd alebo elektróda nie na ten plyn. A tretia — príliš nízka výška prepichu, vtedy dýzu ničí rozstrek.'],
['case','Riadenie vypadáva, ale len pri zapálení oblúka. Čo to je?',
 'Takmer isto elektromagnetické rušenie, nie porucha elektroniky. Vysokofrekvenčné zapaľovanie je silný zdroj širokopásmového šumu. Kľúč je v tom, ako to zákazník opísal: výpadok je viazaný presne na moment zapálenia, nedeje sa náhodne. Pozrel by som uzemnenie — či je do jedného bodu, stav ukostrovacieho kábla, tienenie signálových káblov a či nevedú v rovnakom žľabe so silovými.']
],

en: [
['tech','Which cutting technologies do you know, and how do they differ?',
 'Four. <b>Plasma</b> — an arc melts the metal and swirled gas blows the melt out; it cuts anything conductive. <b>Laser</b> — a focused beam, the highest precision and the narrowest kerf, but limited by thickness. <b>Waterjet</b> — the only cold process: abrasive erodes the material, so there is no heat-affected zone and it cuts almost anything. <b>Oxy-fuel</b> — there the chemistry does the cutting: iron burns in oxygen, which only works on mild steel, but goes up to 300 mm.'],
['tech','When would you choose laser and when plasma?',
 'Up to roughly 25 millimetres laser is faster and gives an incomparably better edge. Above that plasma overtakes it, and beyond 50 laser is not really an option. That boundary keeps moving up as source power grows — ten years ago it sat at 12–15 mm. There is one catch though: on thick material laser pierces slowly, so a part with many holes can come out faster on plasma even if laser cuts the contour quicker.'],
['tech','Why can oxy-fuel not cut stainless steel?',
 'The process depends on the oxide melting below the metal itself — then the oxygen jet blows it away. With iron that holds: iron oxide melts around 1370 °C, iron at 1538. With stainless it is the other way round — chromium oxide is refractory, around 2400 °C. By the time the steel is liquid the oxide is still solid: it forms a crust, blocks the oxygen and the reaction dies. It is the same layer that stops stainless from rusting.'],
['tech','What is kerf, and why is it compensated?',
 'The tool removes a strip of material: 1.5–4 mm with plasma, 0.1–0.4 with laser. If the torch followed the contour exactly, the part would come out smaller by half that width on each side. So the machine offsets the path — outward on an outer contour, inward on holes. Compensation is always switched on during the lead-in, never on the contour itself, or you leave a step where it engages.'],
['tech','Why are inner holes cut before the outer contour?',
 'Because the moment the outer contour is cut, the part drops or shifts. Every hole after that lands in the wrong place, or in the scrap. It is a rule rather than a style — and you can spot the mistake in a program within ten seconds, without running the machine.'],

['plasma','What is a plasma torch made of?',
 'Four consumables. The <b>electrode</b> — copper with a hafnium insert; it is the cathode. The <b>swirl ring</b> — a ring with angled holes that spins the gas and constricts the arc. The <b>nozzle</b> — the orifice the arc is forced through; that constriction is what turns plasma into a cutting tool. The <b>shield cap</b> — shapes the secondary flow and takes the spatter. Their life is counted in pierces, not in metres cut.'],
['plasma','What is the pilot arc and what is it for?',
 'Between the electrode and the plate there is air, which does not conduct — an arc cannot appear out of nothing. So it is struck inside the torch first, between electrode and nozzle. The gas blows it out, creating a conductive channel, and as soon as that reaches the plate the current transfers to it. From then on the transferred arc does the cutting and the nozzle leaves the circuit. If transfer fails, the pilot keeps burning into the nozzle and destroys it in seconds.'],
['plasma','How does torch height control work?',
 'The power source regulates current, not voltage. So voltage is free and tracks arc length directly: a longer arc means higher voltage. The system holds the setpoint by correcting the Z axis, so the torch follows a warped plate on its own. Before cutting there is a separate initial height sensing step. The important part is that consumable wear shifts the voltage at the same height — so when height control "goes mad", I check consumables first, not the sensor.'],
['plasma','Why hafnium in the electrode rather than tungsten?',
 'Tungsten is the better emitter in its own right — it melts around 3400 °C and lasts longer. But it oxidises instantly, so in oxygen or even air it burns away in seconds. Hafnium is the weaker emitter but forms a refractory oxide that survives the process. So hafnium is a compromise forced on us by oxygen. With nitrogen and H35, where there is no oxygen, tungsten is exactly what gets fitted.'],

['laser','What is the difference between a fibre and a CO₂ laser?',
 'Wavelength, and how the beam is delivered. Fibre is around 1.07 µm and the beam travels in an optical fibre — no mirrors, no alignment. Metals absorb that wavelength far better, so it handles even copper and brass, which CO₂ barely cuts, and its efficiency is several times higher. CO₂ is 10.6 µm with a mirror train, but it cuts non-metals well — acrylic, wood, leather. In metal, fibre is now almost universal.'],
['laser','What is the assist gas for?',
 'The beam only melts; the gas blows the melt out of the kerf. It also decides the character of the edge. Oxygen on mild steel enters an exothermic reaction and adds energy itself — faster, but the edge is left oxidised. Nitrogen is inert and only ejects: the edge is clean and ready to weld, but it needs high pressure and more power. Air is the cheap compromise, provided it is dry and oil-free.'],
['laser','How does a laser measure height if there is no arc?',
 'Capacitively. The nozzle acts as a capacitor plate against the sheet: the closer it is, the higher the capacitance. The system holds the setpoint by moving the Z axis. For that to work the nozzle has to be electrically isolated from the head body, and the ceramic ring provides that isolation. So spatter or a crack in the ceramic breaks the measurement: a conductive path appears and the head starts jumping or crashing into the sheet.'],

['elec','What is a servo drive and how does it know its position?',
 'It is a motor in a closed control loop. The controller commands a position, an <b>encoder</b> on the shaft reports the actual one, and the drive continuously corrects the difference. That is exactly what separates it from a stepper: it knows where it really is rather than assuming. If the drive cannot keep up with the command the gap grows and the system raises a following error — usually a mechanical cause: resistance, wear, or wrong parameters.'],
['elec','How would you check a fuse with a multimeter?',
 'Two ways. Isolate the power and measure resistance or continuity: a good fuse reads close to zero ohms and beeps, a blown one reads open. Or, without removing it, measure the voltage across the fuse under load: across a good fuse it is near zero, across a blown one you see the full supply voltage. The second is quicker but demands care, since the circuit is live.'],
['elec','What is the difference between a contactor and a relay?',
 'The principle is the same — an electromagnet closes contacts. The difference is purpose and current. A <b>contactor</b> switches power circuits: motors, heaters, high currents. It has heavy contacts and an arc-quenching chamber, because opening them draws an arc. A <b>relay</b> works in control and signal circuits at low current, and is smaller and cheaper. Put simply: a relay carries a command, a contactor carries power.'],
['elec','Can you read an electrical diagram?',
 'Yes, at the level of tracing a circuit from a symptom: find the component, work out where the supply comes from and where the signal goes, and decide exactly where to measure. I read technical documentation during my studies, and English notation is not a problem. A particular manufacturer\'s conventions I would pick up quickly — the principle is the same everywhere.'],

['think','How do you go about finding the cause of a fault?',
 'I narrow it down rather than guess. I ask what changed since yesterday, when it started, whether it happens every time or intermittently, which material, and what was last replaced. The most important split is whether it happens on every program or only one — that single answer halves the problem. Then I isolate where the cause sits: machine, program, consumables or the customer\'s material. And I always verify the fix — "it works now" is not enough, because if I do not know why, it comes back in a week.'],
['think','Tell us about a difficult problem you solved.',
 'Processing a dataset, I ended up with 568 records instead of 569. Nothing crashed, no error appeared, the program ran normally. The difference only showed up when I compared the result against an independent figure from the source. Since then I do not trust that something is correct just because it ran without complaining — the result has to be checked against something external. In service it is the same: "the machine started up" does not mean the fault is fixed.'],
['think','What do you do when you do not know the answer?',
 'I say I do not know, and immediately say how I will find out: check the documentation, the alarm log, ask a colleague. Inventing something in front of a customer is not an option — a wrong answer costs more than a pause, because they will act on it. An honest "let me check and call you back within the hour" keeps their trust; a guess destroys it for good.'],

['client','How would you explain a technical problem to a non-technical person?',
 'No jargon, and in this order: what happened, why, what we do next, and how long it will take. People do not need a diagnosis, they need to know when they will be producing again. At the end it helps to ask them to repeat the plan in their own words — you see straight away whether you were understood. It comes naturally to me: I studied in Slovak and worked with people daily in hospitality.'],
['client','A customer is shouting because their production has stopped. What do you do?',
 'First I let them finish and I do not argue. Then I acknowledge it directly — yes, the machine is down and it is costing money every hour. And I immediately give something concrete: what I am doing now and when the next update comes. People shout out of uncertainty, not because of the breakdown, and once there is a plan with a time attached the tension drops. Making excuses or looking for someone to blame is the worst possible move at that moment.'],
['client','What if the breakdown was caused by operator error?',
 'I never say "you did it wrong". I say "let us look at what happened together", and we walk through the sequence. People usually reach the conclusion themselves — which is far better than hearing it from me. In the report I describe it neutrally, in facts. And I offer to show the correct procedure so it does not repeat. The goal is that the customer calls us next time instead of staying quiet and breaking something bigger.'],

['org','How do you feel about travelling abroad for work?',
 'Positively, and I have no obstacles — no family commitments or anything else. I have a passport and I enjoy travelling. Five days a month, as your advert states, is completely fine for me. I see business trips as part of this job rather than a sacrifice: it is the part where you learn fastest.'],
['org','Do you have a passport and driving experience?',
 'Yes, I have a passport. A category B licence, and I drive actively. Driving to a customer is not a problem for me.'],
['org','How is your English in practice?',
 'B2. I read technical documentation daily — I work in programming, where everything is in English. Verbally I can hold a working conversation: explain a problem, agree on next steps, ask for clarification. I would not claim to be fluent, but it is enough for customer contact and documentation, and with daily use it will improve quickly.'],
['org','What are your salary expectations?',
 'I am looking at the entry level for a service technician on the Slovak market. What matters more to me is understanding the full package: how many site visits, what the allowances for travel are, and what progression looks like after training. If you give me the range for this position, I will gladly say whether it works for me.'],

['case','A customer says the machine cuts worse than it did yesterday. Where do you start?',
 'With two questions: what changed since yesterday, and whether it happens on every program or only one. If on all of them, the problem is the machine or the consumables — and I check consumables first, because they wear gradually and produce exactly this kind of "sudden" decline. If only on one program, the cause is in the program or its parameters. Then I ask for a photo of the cut edge: the character of the dross and the bevel already tells you which way to look.'],
['case','Parts come out consistently two millimetres undersized. Where will you look?',
 'Almost certainly kerf width in the CAM, not the machine. The key word is "consistently" — a mechanical fault would give scatter, not the same systematic offset on every part. I would check whether all dimensions are undersized or only the outer ones: if the holes are oversized instead, that confirms compensation beyond doubt. Then a test part and a measurement.'],
['case','The operator claims nozzles do not last a week. What are your theories?',
 'The first and most likely is failed starts. If the arc does not transfer to the plate, the pilot keeps burning into the nozzle and destroys it in seconds; a few of those per shift will finish a nozzle. So I check the initial height sensing, the work lead connection and the gas pressure. The second theory is the wrong set fitted: a nozzle not rated for that current, or an electrode not matched to the gas. The third is too low a pierce height, where spatter kills the nozzle.'],
['case','The control system glitches, but only at the moment the arc ignites. What is it?',
 'Almost certainly electromagnetic interference rather than an electronics fault. High-frequency ignition is a powerful source of broadband noise. The clue is in how the customer described it: the glitch is tied precisely to ignition, not happening at random. I would look at the earthing — whether it goes to a single point — the condition of the work lead, the shielding on signal cables, and whether they run in the same tray as the power cables.']
]
};
